import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar/Navbar";
import Footer from "@/components/layout/Footer/Footer";
import { AuthProvider } from "@/context/auth/AuthContext";
import { CourseProvider } from "@/context/course/CourseContext";

export const metadata: Metadata = {
  title: "Aman Tailor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>
          <CourseProvider>
            <Navbar />
            {children}
            <Footer />
          </CourseProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
